[package]
name = "adventofcode-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
rust_decimal = "1.33.1"
rust_decimal_macros = "1.33.1"
rand = "0.8.5"
